source(file.path("..", "..", "src", "common", "logger.R"))
source(file.path("..", "..", "src", "io", "app_files.R"))
source(file.path("..", "..", "src", "io", "io_handler.R"))
# the system under test (sut)
source(file.path("..", "..", "./RFunction.R"))